package com.vention.agroex.util.constant;

public enum ReportType {
    USER_MAX_LOT_QUANTITY,
    USER_MAX_BET_AMOUNT,
    USER_MAX_MONEY_IN_LOTS,
    COUNTRY_LOTS_TOTAL_BET_SUM,
    COUNTRY_LOTS_TOTAL_QUANTITY,
    COUNTRY_LOTS_TOTAL_MONEY_NESTED,
    COUNTRY_LOTS_TOTAL_OWNERS_QUANTITY,

}
