package com.vention.agroex.util.constant;

public enum ReportType {
    USER_MAX_LOT_QUANTITY,
    USER_MAX_BET_AMOUNT,
    USER_MAX_MONEY_IN_LOTS,
    COUNTRY_LOT_PRICE,
    COUNTRY_OWNER_BETS,
    COUNTRY_LOT_COUNT,
    COUNTRY_OWNER_COUNT,
    COUNTRY_PARTICIPANT_COUNT,
    COUNTRY_PARTICIPANT_BETS,

}
